service: app-example

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  logRetentionInDays: 365
  stage: ${opt:stage, 'test'}
  environment: ${file(env.yml):${self:custom.stage}}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
      Resource:
        - "*"

layers:
  dependencyLayer:
    path: "layers/dependencies"
    name: ${self:provider.stage}-dependencyLayer
    compatibleRuntimes:
      - nodejs8.10
    allowedAccounts:
      - "*"

custom:
  stage: ${self:provider.stage}
  prune:
    automatic: true
    number: 3
  webpack:
    includeModules: false

functions:
  - ${ file(./src/http/users/config.yml) }